default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: debug-statements
      - id: name-tests-test
        files: (^|/)tests/(?!fixtures).+\.py$
        args: ['--django']
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.6
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.16.3
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
  - repo: https://github.com/psf/black
    rev: master
    hooks:
      - id: black
        language_version: python3.7
        args: ['--skip-string-normalization']  # we force strings to be single-quoted
